seed: 42

experiment:
  name: act_c3_train_c2_test
  out_dir: ./artifacts/experiments_act

data:
  train_raw_jsonl: ../data_collector/collector3/vr-demonstrations-episodes-20260313_155608.jsonl
  train_h5_path: ./artifacts/datasets/act_collector3_seq.h5

  test_raw_jsonl: ../data_collector/collector2/vr-demonstrations-episodes-20260313_142003.jsonl
  test_h5_path: ./artifacts/datasets/act_collector2_seq.h5

  joint_names:
    - leftShoulder
    - leftUpperArm
    - leftLowerArm
    - leftHand
    - rightShoulder
    - rightUpperArm
    - rightLowerArm
    - rightHand

  use_joint_velocities: true
  include_gripper: false

  seq_len: 16
  stride: 1

model:
  d_model: 128
  nhead: 4
  num_layers: 3
  dim_feedforward: 256
  dropout: 0.1

train:
  batch_size: 128
  epochs: 50
  lr: 0.0003
  weight_decay: 0.00001
  log_interval: 20

export:
  out_path: ./artifacts/exported/policy_act.pt
